name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rye-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Rye and Python
      - name: Install Rye
        uses: phi-friday/install-rye@v2
        with:
          rye_version: "latest" # Optional: specify a version if desired
          python_version: "3.12.5" # Ensure alignment with your Python setup

      # Sync dependencies with Rye
      - name: Sync dependencies
        run: |
          rye sync
